host: 0.0.0.0

title: Chris Harrington
email: chris@harrington.mn
description: >-
  Chris Harrington is an AWS Certified DevOps Engineer in Minneapolis, MN with experience in Go (aka Golang),
  PostgreSQL, JavaScript, C, and other languages.
baseurl: ""
url: "https://chris.harrington.mn"
origin: "https://github.com/ironiridis/portfolio"
mastodon:
  - username: ironiridis
    instance: mspsocial.net
github_username: ironiridis
show_excerpts: true

# Build settings
markdown: kramdown
#theme: minima
# use 2.5.1 with custom-head feature cherrypicked
remote_theme: ironiridis/minima
plugins:
  - jekyll-feed
  - jekyll-gist

minima:
  date_format: "%Y.%m.%d %b %e"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
