host: 0.0.0.0

title: Chris Harrington
email: hire.chris.harrington@gmail.com
description: >-
  Chris Harrington is a developer in Minneapolis, MN with experience in Go (aka Golang),
  PostgreSQL, JavaScript, C, and other languages.
baseurl: ""
url: "https://chris.harrington.mn"
origin: "https://github.com/ironiridis/portfolio"
twitter_username: ironiridis
github_username: ironiridis

# Build settings
markdown: kramdown
#theme: minima
# use 2.5.1 with custom-head feature cherrypicked
remote_theme: ironiridis/minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
